### ISSUE TITLE
Firebase push notifications are intercepted by own app subclass of FirebaseMessagingService

### ISSUE THREAD

**Issue by kaciula** [smooch/smooch-android#40]
My app overrides FirebaseMessagingService and accordingly, it receives all the push messages, even those from smooch so the smooch firebase service is never called.

How to fix this? Can I somehow forward the smooch push notifications to your firebase service from inside my firebase service? I do not want to reimplement myself the smooch logic of parsing the messages and showing a notification. How to solve this @jugarrit ?

EDIT: If I am in the app, when the push message comes, the notification is shown by smooch. However, when I am outside the app, there is no smooch notification.

**Comment by jugarrit** [comment]
Hey @kaciula!

Since you're overriding the service, you can make use of [this helper method](http://docs.smooch.io/api/android/io/smooch/core/FcmService.html#triggerSmoochNotification-java.util.Map-android.content.Context-) to trigger the notification in your `onMessageReceived`.

You might also want to [disable Smooch token registration](http://docs.smooch.io/api/android/io/smooch/core/Settings.html#setFirebaseCloudMessagingAutoRegistrationEnabled-boolean-)

**Comment by kaciula** [comment]
Hi. I have investigated this issue more and here is what I figured out.

Both my app and smooch overrides FirebaseMessagingService and InstanceIdService and both our implementations have the same intent-filter (with the same default priority of 0) declared in the AndroidManifest.xml. Generally, when receiving a matching Intent, Android calls only one of the services (one which is chosen based on internal undefined logic) if there are multiple with the same intent-filter and priority. Obviously this is a problem in our case because of its unpredictability.

I believe you should set a negative priority to FcmService and FcmInstanceIdService so if the main app decides to have their own implementation, it should have their implementation prioritized. Default priority for intent-filter is 0. If you take a look at the base FirebaseMessaggingService and FirebaseInstanceIdService you will see they have their intent-filter priority declared to -500, exactly for the reasons I presented above.

What I did to fix this is I declared a priority of 999 for my implementations of the 2 firebase services so they will have priority over the smooch ones. Also, inside the main app, in its implementation of FirebaseInstanceIdService, I manually call Smooch.setFirebaseCloudMessagingToken(refreshedToken) . Otherwise, smooch push messages won't be received by the app. Disabling or enabling the smooch token registration from the Settings has no effect because, in  this case, the FcmInstanceIdService is never called because of lower priority.

Hope this is clear. Thanks for your time and work.

**Comment by jugarrit** [comment]
I forgot to say you needed to set the Smooch token on registration, deeply sorry about that. This part was known. 
As far as priority is concerned, I was under the impression it was based on the order of the manifest, and that's why the Smooch receiver is generally not called when the app using it also has FCM. 

Thanks for taking the time to write such a detailed post!
