### ISSUE TITLE
Smooch Client doesn't support emojis

### ISSUE THREAD

**Issue by JcMinarro** [smooch/smooch-android#5]
Smooch client doesn't support emojis from slack like :+1:  and It would be cool to add

**Comment by dannytranlx** [comment]
The issue is somewhat from Slack as regular Unicode emojis does render properly. Emojis on Slack are rendered as *Markdown* emojis for OSes compatibility. Even if you are sending the Unicode emoji 😁, it is being converted to `:grin:` which our client doesn't render as a emoji.

We have this on our backlog. Will keep this issue open until then.

Thanks for reporting! :smile:

**Comment by JcMinarro** [comment]
:+1:

**Comment by JcMinarro** [comment]
How is it going???

**Comment by jugarrit** [comment]
It hasn't moved up in priorities, unfortunately! 
We will definitely keep you posted and update the issue when we start work on this.

**Comment by AaronReboot** [comment]
Should be super easy to implement, we handled this in other Slack integrations: just map the markdown emoji to their unicode equivalents

There's a link of the markdown emoji on this Trello blog: http://blog.trello.com/emoji-and-markdown-everywhere

**Comment by wmora** [comment]
Will close as GH issues are for bug reports only. If you still want to request this feature, please visit [our help page](https://smooch.io/help/)

**Comment by gkapatia** [comment]
any update on this guys?

**Comment by rubnov** [comment]
Guys, this issue has been raised over 4 years ago and is simple enough to implement. Could you please look at it again and prioritize it? 

Emojis are a basic and integral part of messaging. As a premium Sunshine customer, it saddens us to see that this important issue has not been prioritized and neglected for so long. We need those emojis !!
