### ISSUE TITLE
getUnreadCount is no working in PushNotificationService

### ISSUE THREAD

**Issue by khataha92** [smooch/smooch-android#59]
I have push notification in my application, but when a new message received while the application closed, I call Smooch.getConversation().getUnreadCount() , but this method is never updated unless I start the application, and it will return the last unread messages before application close. Is there any solution for this issue ?

**Comment by jugarrit** [comment]
Hey there!

The reason the `unreadCount` is not not accurate at this point is because Smooch hasn't yet had a chance to initialize and update the count.

Please try the following:

If you set a [UI Delegate](http://docs.smooch.io/api/android/io/smooch/core/Conversation.html#setSmoochUIDelegate-io.smooch.core.Conversation.Delegate-) you can wait for [onInitializationStatusChanged](http://docs.smooch.io/api/android/io/smooch/core/Conversation.Delegate.html#onInitializationStatusChanged-io.smooch.core.InitializationStatus-) before calling `getUnreadCount`, or even better, [onUnreadCountChanged](http://docs.smooch.io/api/android/io/smooch/core/Conversation.Delegate.html#onUnreadCountChanged-io.smooch.core.Conversation-int-) to see when the count changes.

**Comment by adicatur** [comment]
HI @jugarrit, 
how if I dont use UI delegate, I use smooch defualt UI, is there any solution ? I have same issue when my apps is closed, I get notification from smooch while I log getConversation().getUnreadCount(), but yet updated the number message. 

thanks

**Comment by jugarrit** [comment]
@adicatur you can still use the UI Delegate even if you're using the default Smooch UI. This is still the best way to get an up to date count.

**Comment by adicatur** [comment]
hi @jugarrit, sorry can you give example using UI delegate, I already implement UI delegate in new activity, but how to set layout converstation activity into current activity y, I look into demo, but yet doesnt exist ?

thanks

**Comment by jugarrit** [comment]
@adicatur I believe I misspoke, sorry about that.
In the original post https://github.com/smooch/smooch-android/issues/59#issuecomment-261273128 I said to use the UI Delegate and pointed to the method `setSmoochUIDelegate`.

Instead of using this method, it would be more appropriate to simply use [setDelegate](https://docs.smooch.io/api/android/io/smooch/core/Conversation.html#setDelegate-io.smooch.core.Conversation.Delegate-) as `setSmoochUIDelegate` is intended for those who wish to build their own UI.

As for an example of how to use it, check out [this gist](https://gist.github.com/jugarrit/027e5f6689457b0314672f59ac5a6c8a)

**Comment by adicatur** [comment]
"setmoochUIDelegate is intended for those who wish to build their own UI."

so means we cannot use default UI which refers to ConverstationActivity to implement delegate y ? 

the only solution is we build own UI then set delegate so we can listen all event, isn't?

**Comment by wmora** [comment]
Hi @adicatur, if I understand correctly you are using `ConversationActivity` from the SDK and would like to listen to all events. If so, you can do as @jugarrit suggested and provide your own delegate using [setDelegate](https://docs.smooch.io/api/android/io/smooch/core/Conversation.html#setDelegate-io.smooch.core.Conversation.Delegate-) somewhere in your application.

For example, you could have something like this in your `Application` class:

```java
public class ShellApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();

        // Initialize Smooch
        Smooch.init(this, new Settings("my_app_token"));
        // Provide your own delegate
        Smooch.getConversation().setDelegate(new MyDelegate());
    }
}
```

And `MyDelegate` would be something like:

```java
public class MyDelegate implements Conversation.Delegate {

    // Provide an implementation for whatever events you're interested in    

    @Override
    public void onMessagesReceived(Conversation conversation, List<Message> messages) {

    }

    @Override
    public void onUnreadCountChanged(Conversation conversation, int unreadCount) {

    }

    @Override
    public void onMessagesReset(Conversation conversation, List<Message> messages) {

    }

    @Override
    public void onMessageSent(Message message, MessageUploadStatus status) {

    }

    @Override
    public void onInitializationStatusChanged(InitializationStatus status) {

    }

    @Override
    public void onPaymentProcessed(MessageAction messageAction, PaymentStatus status) {

    }

    @Override
    public boolean shouldTriggerAction(MessageAction messageAction) {
        return false;
    }

    @Override
    public void onCardSummaryLoaded(CardSummary cardSummary) {

    }

    @Override
    public void onSmoochConnectionStatusChanged(SmoochConnectionStatus status) {

    }

    @Override
    public void onSmoochShown() {

    }

    @Override
    public void onSmoochHidden() {

    }
}
```

**Comment by adicatur** [comment]
Yes, Cool thanks @wmora
