### ISSUE TITLE
Smooch.getConversation().getMessages() return empty on first time opening app

### ISSUE THREAD

**Issue by Arsyady** [smooch/smooch-android#87]
I have a weird issue. When your app is opened for the first time, Conversation.getMessages() return empty messages. Same case if I reopen the app **after** clearing it from recent apps. But when I exit the app **without** clearing it from recent apps and open it again, the message appears fine. Am I missing something?

**Comment by wmora** [comment]
Hi there!

> When your app is opened for the first time, Conversation.getMessages() return empty messages. Same case if I reopen the app after clearing it from recent apps 

When the app process is first started the SDK needs to fetch the messages from the server as part of its initialization, so there's a possibility that calling `Conversation.getMessages()` will return an empty array. Implement [`Conversation.Delegate.onInitializationStatusChanged`](https://docs.smooch.io/api/android/io/smooch/core/Conversation.Delegate.html#onInitializationStatusChanged-io.smooch.core.InitializationStatus-) and wait for the `Success` event to get the latest messages from the server.

> But when I exit the app without clearing it from recent apps and open it again, the message appears fine

When the app is sent to background and later resumed, the SDK will still have the latest copy of `Conversation.getMessages()` from the initialization previously mentioned and that's why you see them right away.
